# Q1

Write a numpy program to create a structured array from given student name ,height,class and their data types,then sort the array on height;

In [3]:
import numpy as np
student=[('hajar',163,"AI1"),("magdy",145,"KG1"),("Yazn",180,"KG2"),("Ahmed",185,"DR1"),("Aliaa",150,"PR1")]
data_type = [('name', 'S15'), ('height', int),('class', 'S5')]
students = np.array(student, dtype=data_type)
print("Original array:")
print(students)
print("________________________________________________")
print("Sort by height")
print(np.sort(students, order='height'))  

Original array:
[(b'hajar', 163, b'AI1') (b'magdy', 145, b'KG1') (b'Yazn', 180, b'KG2')
 (b'Ahmed', 185, b'DR1') (b'Aliaa', 150, b'PR1')]
________________________________________________
Sort by height
[(b'magdy', 145, b'KG1') (b'Aliaa', 150, b'PR1') (b'hajar', 163, b'AI1')
 (b'Yazn', 180, b'KG2') (b'Ahmed', 185, b'DR1')]


# Q2: Using Both Numpy and Scipy
Kindly solve the following equations using SciPy:


x+2y−3z+2w=30

2x−5y+4z+9w=4

−5x+40y−z−20w=−6

5x−4y−z+60w=5

##### Method NUM1

In [4]:
A=np.array([[1,2,-3,2],[2,-5,4,9],[-5,40,-1,-20],[5,-4,-1,60]])
A.shape

(4, 4)

In [5]:
b=np.array([[30],[4],[-6],[5]])
b.shape

(4, 1)

In [6]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.60706806,  0.43926702,  0.01649215, -0.08062827],
       [ 0.04777487,  0.04319372,  0.02814136,  0.0013089 ],
       [-0.13219895,  0.15445026,  0.02486911, -0.0104712 ],
       [-0.04960733, -0.03115183,  0.00091623,  0.02329843]])

In [7]:
A_inv.dot(b)

array([[19.46701571],
       [ 1.44371728],
       [-3.54973822],
       [-1.50183246]])

#### Method NUM2

In [8]:
np.linalg.solve(A, b)

array([[19.46701571],
       [ 1.44371728],
       [-3.54973822],
       [-1.50183246]])

# Q3: Implement the L1 and L2 loss functions


Exercise: Implement the numpy vectorized version of the L1 loss. You may find the function abs(x) (absolute value of x) useful.

Reminder:

The loss is used to evaluate the performance of your model. The bigger your loss is, the more different your predictions (
^
y
) are from the true values (
y
). In deep learning, you use optimization algorithms like Gradient Descent to train your model and to minimize the cost.
L1 loss is defined as:

# The L1 norm is calculated as the sum of the absolute vector values 

In [9]:
def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    loss = None
    loss =np.abs(y-yhat).sum()
    ### END CODE HERE ###
    
    return loss

In [10]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y    = np.array([1 ,  0 ,  0 ,  1, 1])

l1_loss = L1(yhat,y)
print("L1 = " + str(l1_loss))

L1 = 1.1


Exercise: Implement the numpy vectorized version of the L2 loss. There are several way of implementing the L2 loss but you may find the function np.dot() useful. As a reminder,

In [11]:
def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    
    ### START CODE HERE ### (≈ 1 line of code)
    loss = None
    loss = np.dot(np.abs(yhat-y),np.abs(yhat-y))
    ### END CODE HERE ###
    
    return loss

In [12]:
yhat = np.array([.9, 0.2, 0.1, .4, .9])
y    = np.array([1 ,  0 ,  0 ,  1, 1])

l2_loss = L2(yhat,y)

print("L2 = " + str(l2_loss))

L2 = 0.43


## Q4: Comparing the dot product using parallelism in Python vs numpy_dot_product vs using the for_loop and compute the time needed for each.

In [13]:
def slow_dot_product(a, b):
    result = 0
    for i in range(len(a)):
        result += a[i] * b[i]
    return result

In [15]:
import time

In [22]:
a=np.array([[1,2],[3,4]])
b=np.array([[1,2],[3,4]])

In [23]:
tic = time.process_time()
slow_dot_product(a, b)
toc = time.process_time()
dt1 = toc - tic

print("Time in sec:", dt1)

Time in sec: 0.0


In [24]:
tic = time.process_time()
a @ b    
toc = time.process_time()
dt1 = toc - tic

print("Time in sec:", dt1)

Time in sec: 0.0


In [28]:
# number of experiments 
T = 1000

a = np.random.randn(10_000)
b = np.random.randn(10_000)

In [26]:
tic = time.process_time()

for t in range(T):
    slow_dot_product(a, b)
    
toc = time.process_time()
dt1 = toc - tic

print("Time in sec:", dt1)

Time in sec: 7.140625


In [29]:
tic = time.process_time()

for t in range(T):
    a @ b
    
toc = time.process_time()
dt1 = toc - tic

print("Time in sec:", dt1)

Time in sec: 0.0
